name: Build and generate data

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Build and generate data with Gradle
        run: |
          chmod +x gradlew
          ./gradlew generateData
        shell: bash
      - name: Upload the JAR and data
        uses: actions/upload-artifact@v2
        with:
          path: |
            build/libs/*
            generated/*
